# muscles_data.py
# 肌肉資料庫：起點、終點、神經支配、功能
# 動作查詢對照表：動作 → 主動肌、協同肌、拮抗肌
# 資料來源：Kenhub, Gray's Anatomy, Wikipedia

# ─────────────────────────────────────────
# 肌肉資料庫
# ─────────────────────────────────────────
MUSCLES = {

    # ══════════════ 臀部肌群 Gluteal ══════════════
    "gluteus maximus": {
        "zh": "臀大肌",
        "origin": "Lateroposterior surface of sacrum and coccyx; Gluteal surface of ilium (posterior to posterior gluteal line); Thoracolumbar fascia; Sacrotuberous ligament",
        "insertion": "Iliotibial tract; Gluteal tuberosity of femur",
        "innervation": "Inferior gluteal nerve (L5-S2)",
        "functions": ["Hip extension", "Hip external rotation", "Hip abduction (superior part)", "Hip adduction (inferior part)"],
        "antagonists": ["Iliopsoas", "Rectus femoris", "Tensor fasciae latae"],
        "region": "Gluteal",
    },
    "gluteus medius": {
        "zh": "臀中肌",
        "origin": "Gluteal surface of ilium (between anterior and posterior gluteal lines)",
        "insertion": "Lateral aspect of greater trochanter of femur",
        "innervation": "Superior gluteal nerve (L4-S1)",
        "functions": ["Hip abduction", "Hip internal rotation (anterior fibers)", "Pelvis stabilization"],
        "antagonists": ["Hip adductors", "Gluteus maximus"],
        "region": "Gluteal",
    },
    "gluteus minimus": {
        "zh": "臀小肌",
        "origin": "Gluteal surface of ilium (between anterior and inferior gluteal lines)",
        "insertion": "Anterior aspect of greater trochanter of femur",
        "innervation": "Superior gluteal nerve (L4-S1)",
        "functions": ["Hip abduction", "Hip internal rotation (anterior fibers)", "Pelvis stabilization"],
        "antagonists": ["Hip adductors"],
        "region": "Gluteal",
    },
    "tensor fasciae latae": {
        "zh": "闊筋膜張肌",
        "origin": "Anterior superior iliac spine (ASIS); Outer lip of iliac crest",
        "insertion": "Iliotibial tract",
        "innervation": "Superior gluteal nerve (L4-S1)",
        "functions": ["Hip internal rotation", "Hip abduction (weak)", "Knee external rotation", "Hip and knee stabilization"],
        "antagonists": ["Hip adductors", "Hip external rotators"],
        "region": "Gluteal",
    },

    # ══════════════ 髖部深層 Deep Hip ══════════════
    "iliacus": {
        "zh": "髂肌",
        "origin": "Iliac fossa",
        "insertion": "Lesser trochanter of femur",
        "innervation": "Femoral nerve (L2-L4)",
        "functions": ["Hip flexion", "Hip external rotation", "Trunk flexion"],
        "antagonists": ["Gluteus maximus", "Hamstrings"],
        "region": "Deep Hip",
    },
    "psoas major": {
        "zh": "腰大肌",
        "origin": "Vertebral bodies of T12-L4; Intervertebral discs T12-L4; Costal processes L1-L5",
        "insertion": "Lesser trochanter of femur",
        "innervation": "Anterior rami of spinal nerves L1-L3",
        "functions": ["Hip flexion", "Trunk flexion", "Hip external rotation", "Trunk lateral flexion"],
        "antagonists": ["Gluteus maximus", "Hamstrings"],
        "region": "Deep Hip",
    },
    "psoas minor": {
        "zh": "腰小肌",
        "origin": "Vertebral bodies of T12 and L1",
        "insertion": "Iliopubic eminence; Pectineal line of pubis",
        "innervation": "Anterior rami of spinal nerves L1-L3",
        "functions": ["Trunk flexion (weak)", "Trunk lateral flexion"],
        "antagonists": ["Erector spinae"],
        "region": "Deep Hip",
    },
    "iliopsoas": {
        "zh": "髂腰肌（髂肌＋腰大肌）",
        "origin": "Iliac fossa (iliacus); Vertebral bodies T12-L4 (psoas major)",
        "insertion": "Lesser trochanter of femur",
        "innervation": "Femoral nerve (L2-L4); Anterior rami L1-L3",
        "functions": ["Hip flexion (primary hip flexor)", "Trunk flexion", "Hip external rotation"],
        "antagonists": ["Gluteus maximus", "Semimembranosus", "Semitendinosus", "Biceps femoris"],
        "region": "Deep Hip",
    },
    "piriformis": {
        "zh": "梨狀肌",
        "origin": "Anterior surface of sacrum (S2-S4); Gluteal surface of ilium; Sacrotuberous ligament",
        "insertion": "Apex of greater trochanter of femur",
        "innervation": "Nerve to piriformis (S1-S2)",
        "functions": ["Hip external rotation", "Hip abduction (from flexed hip)", "Femoral head stabilization"],
        "antagonists": ["Gluteus medius (anterior)", "Gluteus minimus", "Tensor fasciae latae"],
        "region": "Deep Hip",
    },
    "obturator internus": {
        "zh": "閉孔內肌",
        "origin": "Ischiopubic ramus; Posterior surface of obturator membrane",
        "insertion": "Medial surface of greater trochanter of femur",
        "innervation": "Nerve to obturator internus (L5-S1)",
        "functions": ["Hip external rotation", "Hip abduction (from flexed hip)", "Femoral head stabilization"],
        "antagonists": ["Hip internal rotators"],
        "region": "Deep Hip",
    },
    "obturator externus": {
        "zh": "閉孔外肌",
        "origin": "Anterior surface of obturator membrane; Bony boundaries of obturator foramen",
        "insertion": "Trochanteric fossa of femur",
        "innervation": "Obturator nerve (L3-L4)",
        "functions": ["Hip external rotation", "Hip abduction (from flexed hip)", "Femoral head stabilization"],
        "antagonists": ["Hip internal rotators"],
        "region": "Deep Hip",
    },
    "superior gemellus": {
        "zh": "上孖肌",
        "origin": "Ischial spine",
        "insertion": "Medial surface of greater trochanter of femur (via obturator internus tendon)",
        "innervation": "Nerve to obturator internus (L5-S1)",
        "functions": ["Hip external rotation", "Hip abduction (from flexed hip)", "Femoral head stabilization"],
        "antagonists": ["Hip internal rotators"],
        "region": "Deep Hip",
    },
    "inferior gemellus": {
        "zh": "下孖肌",
        "origin": "Ischial tuberosity",
        "insertion": "Medial surface of greater trochanter of femur (via obturator internus tendon)",
        "innervation": "Nerve to quadratus femoris (L4-S1)",
        "functions": ["Hip external rotation", "Hip abduction (from flexed hip)", "Femoral head stabilization"],
        "antagonists": ["Hip internal rotators"],
        "region": "Deep Hip",
    },
    "quadratus femoris": {
        "zh": "股方肌",
        "origin": "Ischial tuberosity",
        "insertion": "Intertrochanteric crest of femur",
        "innervation": "Nerve to quadratus femoris (L4-S1)",
        "functions": ["Hip external rotation", "Femoral head stabilization"],
        "antagonists": ["Hip internal rotators"],
        "region": "Deep Hip",
    },

    # ══════════════ 大腿前側 Anterior Thigh ══════════════
    "sartorius": {
        "zh": "縫匠肌",
        "origin": "Anterior superior iliac spine (ASIS)",
        "insertion": "Proximal end of tibia below medial condyle (via pes anserinus)",
        "innervation": "Femoral nerve (L2-L4)",
        "functions": ["Hip flexion", "Hip abduction", "Hip external rotation", "Knee flexion", "Knee internal rotation"],
        "antagonists": ["Hip adductors", "Quadriceps femoris"],
        "region": "Anterior Thigh",
    },
    "rectus femoris": {
        "zh": "股直肌",
        "origin": "Anterior inferior iliac spine; Supraacetabular groove",
        "insertion": "Tibial tuberosity (via patellar ligament); Patella",
        "innervation": "Femoral nerve (L2-L4)",
        "functions": ["Hip flexion", "Knee extension"],
        "antagonists": ["Hamstrings", "Gluteus maximus"],
        "region": "Anterior Thigh",
    },
    "vastus intermedius": {
        "zh": "股中間肌",
        "origin": "Anterior surface of femoral shaft",
        "insertion": "Tibial tuberosity (via patellar ligament); Patella",
        "innervation": "Femoral nerve (L2-L4)",
        "functions": ["Knee extension"],
        "antagonists": ["Hamstrings"],
        "region": "Anterior Thigh",
    },
    "vastus lateralis": {
        "zh": "股外側肌",
        "origin": "Linea aspera of femur (lateral lip); Greater trochanter of femur",
        "insertion": "Tibial tuberosity (via patellar ligament); Patella; Lateral condyle of tibia",
        "innervation": "Femoral nerve (L2-L4)",
        "functions": ["Knee extension"],
        "antagonists": ["Hamstrings"],
        "region": "Anterior Thigh",
    },
    "vastus medialis": {
        "zh": "股內側肌（VMO）",
        "origin": "Intertrochanteric line; Spiral line; Linea aspera (medial lip); Medial supracondylar line",
        "insertion": "Tibial tuberosity (via patellar ligament); Patella; Medial condyle of tibia",
        "innervation": "Femoral nerve (L2-L4)",
        "functions": ["Knee extension", "Patellar medial stabilization (VMO)"],
        "antagonists": ["Hamstrings"],
        "region": "Anterior Thigh",
    },

    # ══════════════ 大腿內側 Medial Thigh ══════════════
    "pectineus": {
        "zh": "恥骨肌",
        "origin": "Superior pubic ramus (Pectineal line of pubis)",
        "insertion": "Pectineal line of femur; Linea aspera of femur",
        "innervation": "Femoral nerve (L2-L3); Obturator nerve (L2-L3)",
        "functions": ["Hip adduction", "Hip flexion", "Hip medial rotation (weak)", "Pelvis stabilization"],
        "antagonists": ["Hip abductors"],
        "region": "Medial Thigh",
    },
    "adductor magnus": {
        "zh": "內收大肌",
        "origin": "Adductor part: Inferior pubic ramus, Ischial ramus; Ischiocondylar part: Ischial tuberosity",
        "insertion": "Adductor part: Gluteal tuberosity, Linea aspera, Medial supracondylar line; Ischiocondylar part: Adductor tubercle",
        "innervation": "Adductor part: Obturator nerve (L2-L4); Ischiocondylar part: Tibial division of sciatic nerve (L4)",
        "functions": ["Hip adduction", "Hip flexion (adductor part)", "Hip medial rotation (adductor part)", "Hip extension (ischiocondylar part)", "Pelvis stabilization"],
        "antagonists": ["Hip abductors", "Gluteus medius"],
        "region": "Medial Thigh",
    },
    "adductor longus": {
        "zh": "內收長肌",
        "origin": "Anterior body of pubis",
        "insertion": "Linea aspera of femur (medial lip)",
        "innervation": "Obturator nerve (L2-L4)",
        "functions": ["Hip adduction", "Hip flexion", "Hip medial rotation (weak)", "Pelvis stabilization"],
        "antagonists": ["Gluteus medius", "Gluteus minimus", "Tensor fasciae latae"],
        "region": "Medial Thigh",
    },
    "adductor brevis": {
        "zh": "內收短肌",
        "origin": "Anterior body of pubis; Inferior pubic ramus",
        "insertion": "Linea aspera of femur (medial lip)",
        "innervation": "Obturator nerve (L2-L4)",
        "functions": ["Hip adduction", "Hip flexion", "Hip medial rotation (weak)"],
        "antagonists": ["Hip abductors"],
        "region": "Medial Thigh",
    },
    "adductor minimus": {
        "zh": "內收小肌",
        "origin": "Inferior pubic ramus",
        "insertion": "Gluteal tuberosity of femur",
        "innervation": "Obturator nerve (L2-L4)",
        "functions": ["Hip adduction", "Hip medial rotation (weak)"],
        "antagonists": ["Hip abductors"],
        "region": "Medial Thigh",
    },
    "gracilis": {
        "zh": "股薄肌",
        "origin": "Anterior body of pubis; Inferior pubic ramus; Ischial ramus",
        "insertion": "Medial surface of proximal tibia (via pes anserinus)",
        "innervation": "Obturator nerve (L2-L3)",
        "functions": ["Hip adduction", "Hip flexion", "Knee flexion", "Knee internal rotation"],
        "antagonists": ["Hip abductors", "Quadriceps femoris"],
        "region": "Medial Thigh",
    },

    # ══════════════ 大腿後側 Hamstrings ══════════════
    "semimembranosus": {
        "zh": "半膜肌",
        "origin": "Superolateral impression of ischial tuberosity",
        "insertion": "Medial condyle of tibia",
        "innervation": "Tibial division of sciatic nerve (L5-S2)",
        "functions": ["Hip extension", "Hip internal rotation", "Knee flexion", "Knee internal rotation", "Pelvis stabilization"],
        "antagonists": ["Iliopsoas", "Rectus femoris", "Quadriceps femoris"],
        "region": "Posterior Thigh",
    },
    "semitendinosus": {
        "zh": "半腱肌",
        "origin": "Posteromedial impression of ischial tuberosity",
        "insertion": "Proximal end of tibia below medial condyle (via pes anserinus)",
        "innervation": "Tibial division of sciatic nerve (L5-S2)",
        "functions": ["Hip extension", "Hip internal rotation", "Knee flexion", "Knee internal rotation", "Pelvis stabilization"],
        "antagonists": ["Iliopsoas", "Rectus femoris", "Quadriceps femoris"],
        "region": "Posterior Thigh",
    },
    "biceps femoris": {
        "zh": "股二頭肌",
        "origin": "Long head: Inferomedial impression of ischial tuberosity, Sacrotuberous ligament; Short head: Linea aspera (lateral lip), Lateral supracondylar line",
        "insertion": "Lateral aspect of head of fibula",
        "innervation": "Long head: Tibial division of sciatic nerve (L5-S2); Short head: Common fibular division (L5-S2)",
        "functions": ["Hip extension (long head)", "Hip external rotation", "Knee flexion", "Knee external rotation", "Pelvis stabilization"],
        "antagonists": ["Iliopsoas (long head)", "Quadriceps femoris"],
        "region": "Posterior Thigh",
    },

    # ══════════════ 小腿前側 Anterior Leg ══════════════
    "tibialis anterior": {
        "zh": "脛骨前肌",
        "origin": "Lateral tibial condyle; Proximal half of lateral surface of tibia; Interosseous membrane",
        "insertion": "Medial cuneiform bone; Base of metatarsal bone 1",
        "innervation": "Deep fibular nerve (L4-L5)",
        "functions": ["Foot dorsiflexion", "Foot inversion", "Supports medial longitudinal arch"],
        "antagonists": ["Gastrocnemius", "Soleus", "Tibialis posterior"],
        "region": "Anterior Leg",
    },
    "extensor hallucis longus": {
        "zh": "伸拇長肌",
        "origin": "Middle third of medial surface of fibula; Interosseous membrane",
        "insertion": "Base of distal phalanx of great toe",
        "innervation": "Deep fibular nerve (L5-S1)",
        "functions": ["Great toe extension", "Foot dorsiflexion"],
        "antagonists": ["Flexor hallucis longus"],
        "region": "Anterior Leg",
    },
    "extensor digitorum longus": {
        "zh": "伸趾長肌",
        "origin": "Proximal half of medial surface of fibula; Lateral tibial condyle; Interosseous membrane",
        "insertion": "Distal and middle phalanges of digits 2-5",
        "innervation": "Deep fibular nerve (L5-S1)",
        "functions": ["Toe extension (digits 2-5)", "Foot dorsiflexion", "Foot eversion"],
        "antagonists": ["Flexor digitorum longus"],
        "region": "Anterior Leg",
    },
    "fibularis tertius": {
        "zh": "第三腓骨肌",
        "origin": "Distal third of medial surface of fibula; Anterior intermuscular septum",
        "insertion": "Dorsal surface of base of metatarsal bone 5",
        "innervation": "Deep fibular nerve (L5-S1)",
        "functions": ["Foot dorsiflexion", "Foot eversion"],
        "antagonists": ["Tibialis posterior"],
        "region": "Anterior Leg",
    },

    # ══════════════ 小腿外側 Lateral Leg ══════════════
    "fibularis longus": {
        "zh": "腓骨長肌",
        "origin": "Head of fibula; Proximal 2/3 of lateral surface of fibula; Anterior and posterior intermuscular septa",
        "insertion": "Medial cuneiform bone; Metatarsal bone 1",
        "innervation": "Superficial fibular nerve (L5-S1)",
        "functions": ["Foot plantarflexion", "Foot eversion", "Supports longitudinal and transverse arches"],
        "antagonists": ["Tibialis anterior", "Tibialis posterior"],
        "region": "Lateral Leg",
    },
    "fibularis brevis": {
        "zh": "腓骨短肌",
        "origin": "Distal 2/3 of lateral surface of fibula; Anterior intermuscular septum",
        "insertion": "Tuberosity of metatarsal bone 5",
        "innervation": "Superficial fibular nerve (L5-S1)",
        "functions": ["Foot plantarflexion", "Foot eversion"],
        "antagonists": ["Tibialis anterior", "Tibialis posterior"],
        "region": "Lateral Leg",
    },

    # ══════════════ 小腿後側 Posterior Leg ══════════════
    "gastrocnemius": {
        "zh": "腓腸肌",
        "origin": "Lateral head: Posterolateral surface of lateral femoral condyle; Medial head: Posterior surface of medial femoral condyle, Popliteal surface of femoral shaft",
        "insertion": "Posterior surface of calcaneus (via calcaneal/Achilles tendon)",
        "innervation": "Tibial nerve (S1-S2)",
        "functions": ["Foot plantarflexion", "Knee flexion"],
        "antagonists": ["Tibialis anterior", "Quadriceps femoris"],
        "region": "Posterior Leg",
    },
    "soleus": {
        "zh": "比目魚肌",
        "origin": "Soleal line; Medial border of tibia; Head of fibula; Posterior border of fibula",
        "insertion": "Posterior surface of calcaneus (via calcaneal/Achilles tendon)",
        "innervation": "Tibial nerve (S1-S2)",
        "functions": ["Foot plantarflexion"],
        "antagonists": ["Tibialis anterior"],
        "region": "Posterior Leg",
    },
    "plantaris": {
        "zh": "蹠肌",
        "origin": "Lateral supracondylar line of femur; Oblique popliteal ligament",
        "insertion": "Posterior surface of calcaneus (via calcaneal tendon)",
        "innervation": "Tibial nerve (S1-S2)",
        "functions": ["Foot plantarflexion", "Knee flexion"],
        "antagonists": ["Tibialis anterior"],
        "region": "Posterior Leg",
    },
    "popliteus": {
        "zh": "膕肌",
        "origin": "Lateral femoral condyle; Posterior horn of lateral meniscus",
        "insertion": "Posterior surface of proximal tibia",
        "innervation": "Tibial nerve (L5-S2)",
        "functions": ["Unlocks knee joint (internal rotation of tibia)", "Knee joint stabilization"],
        "antagonists": ["Biceps femoris (rotation component)"],
        "region": "Posterior Leg",
    },
    "tibialis posterior": {
        "zh": "脛骨後肌",
        "origin": "Posterior surface of tibia; Posterior surface of fibula; Interosseous membrane",
        "insertion": "Tuberosity of navicular; All cuneiform bones; Bases of metatarsal bones 2-4",
        "innervation": "Tibial nerve (L4-L5)",
        "functions": ["Foot plantarflexion", "Foot inversion", "Supports medial longitudinal arch"],
        "antagonists": ["Fibularis longus", "Fibularis brevis", "Tibialis anterior (inversion)"],
        "region": "Posterior Leg",
    },
    "flexor digitorum longus": {
        "zh": "屈趾長肌",
        "origin": "Posterior surface of tibia (inferior to soleal line)",
        "insertion": "Bases of distal phalanges of digits 2-5",
        "innervation": "Tibial nerve (L5-S2)",
        "functions": ["Toe flexion (digits 2-5)", "Foot plantarflexion", "Foot inversion"],
        "antagonists": ["Extensor digitorum longus"],
        "region": "Posterior Leg",
    },
    "flexor hallucis longus": {
        "zh": "屈拇長肌",
        "origin": "Distal 2/3 of posterior surface of fibula; Interosseous membrane",
        "insertion": "Base of distal phalanx of great toe",
        "innervation": "Tibial nerve (S2-S3)",
        "functions": ["Great toe flexion", "Foot plantarflexion", "Foot inversion"],
        "antagonists": ["Extensor hallucis longus"],
        "region": "Posterior Leg",
    },

    # ══════════════ 旋轉肌袖 Rotator Cuff ══════════════
    "supraspinatus": {
        "zh": "棘上肌",
        "origin": "Supraspinous fossa of scapula",
        "insertion": "Superior facet of greater tubercle of humerus",
        "innervation": "Suprascapular nerve (C4-C6)",
        "functions": ["Shoulder abduction (initiation 0-15°)", "Glenohumeral joint stabilization"],
        "antagonists": ["Latissimus dorsi", "Pectoralis major"],
        "region": "Rotator Cuff",
    },
    "infraspinatus": {
        "zh": "棘下肌",
        "origin": "Infraspinous fossa of scapula",
        "insertion": "Middle facet of greater tubercle of humerus",
        "innervation": "Suprascapular nerve (C5-C6)",
        "functions": ["Shoulder external rotation", "Glenohumeral joint stabilization"],
        "antagonists": ["Subscapularis", "Pectoralis major", "Latissimus dorsi"],
        "region": "Rotator Cuff",
    },
    "teres minor": {
        "zh": "小圓肌",
        "origin": "Posterior surface of scapula (lateral border, upper two-thirds)",
        "insertion": "Inferior facet of greater tubercle of humerus",
        "innervation": "Axillary nerve (C5-C6)",
        "functions": ["Shoulder external rotation", "Shoulder adduction", "Glenohumeral joint stabilization"],
        "antagonists": ["Subscapularis", "Pectoralis major"],
        "region": "Rotator Cuff",
    },
    "subscapularis": {
        "zh": "肩胛下肌",
        "origin": "Subscapular fossa of scapula",
        "insertion": "Lesser tubercle of humerus",
        "innervation": "Upper and lower subscapular nerves (C5-C7)",
        "functions": ["Shoulder internal rotation", "Shoulder adduction", "Glenohumeral joint stabilization"],
        "antagonists": ["Infraspinatus", "Teres minor", "Posterior deltoid"],
        "region": "Rotator Cuff",
    },

    # ══════════════ 肩部 Shoulder ══════════════
    "deltoid": {
        "zh": "三角肌",
        "origin": "Anterior part: Lateral third of clavicle; Middle part: Acromion; Posterior part: Spine of scapula",
        "insertion": "Deltoid tuberosity of humerus",
        "innervation": "Axillary nerve (C5-C6)",
        "functions": ["Shoulder abduction (all parts)", "Shoulder flexion (anterior)", "Shoulder extension (posterior)", "Shoulder internal rotation (anterior)", "Shoulder external rotation (posterior)"],
        "antagonists": ["Latissimus dorsi (abduction)", "Pectoralis major"],
        "region": "Shoulder",
    },
    "teres major": {
        "zh": "大圓肌",
        "origin": "Inferior angle and posterior surface of scapula (lower third)",
        "insertion": "Medial lip of intertubercular sulcus of humerus",
        "innervation": "Lower subscapular nerve (C5-C7)",
        "functions": ["Shoulder extension", "Shoulder adduction", "Shoulder internal rotation"],
        "antagonists": ["Deltoid", "Supraspinatus", "External rotators"],
        "region": "Shoulder",
    },
    "coracobrachialis": {
        "zh": "喙肱肌",
        "origin": "Coracoid process of scapula",
        "insertion": "Medial surface of humerus (midshaft)",
        "innervation": "Musculocutaneous nerve (C5-C7)",
        "functions": ["Shoulder flexion", "Shoulder adduction"],
        "antagonists": ["Deltoid (abduction)", "Latissimus dorsi"],
        "region": "Shoulder",
    },
    "pectoralis major": {
        "zh": "胸大肌",
        "origin": "Clavicular head: Sternal half of clavicle; Sternocostal head: Sternum, Costal cartilages of ribs 1-7 (true ribs); Abdominal part: Aponeurosis of external abdominal oblique",
        "insertion": "Lateral lip of intertubercular sulcus of humerus",
        "innervation": "Medial and lateral pectoral nerves (C5-T1)",
        "functions": ["Shoulder adduction", "Shoulder internal rotation", "Shoulder flexion (clavicular head)", "Shoulder extension (sternocostal head from flexion)"],
        "antagonists": ["Deltoid (abduction)", "Infraspinatus", "Teres minor"],
        "region": "Chest",
    },
    "pectoralis minor": {
        "zh": "胸小肌",
        "origin": "Anterior surfaces of ribs 3-5 (near costal cartilage)",
        "insertion": "Coracoid process of scapula",
        "innervation": "Medial pectoral nerve (C8-T1)",
        "functions": ["Scapular protraction", "Scapular depression", "Scapular downward rotation", "Rib elevation (forced inspiration)"],
        "antagonists": ["Trapezius (lower)", "Serratus anterior"],
        "region": "Chest",
    },
    "latissimus dorsi": {
        "zh": "背闊肌",
        "origin": "Spinous processes T7-L5 (sometimes to sacrum); Thoracolumbar fascia; Iliac crest (posterior third); Last 3-4 ribs; Inferior angle of scapula (sometimes)",
        "insertion": "Floor of intertubercular sulcus of humerus",
        "innervation": "Thoracodorsal nerve (C6-C8)",
        "functions": ["Shoulder extension", "Shoulder adduction", "Shoulder internal rotation"],
        "antagonists": ["Anterior deltoid", "Pectoralis major (flexion)"],
        "region": "Back",
    },
    "serratus anterior": {
        "zh": "前鋸肌",
        "origin": "Lateral surfaces of ribs 1-8 or 9",
        "insertion": "Costal surface of medial border of scapula",
        "innervation": "Long thoracic nerve (C5-C7)",
        "functions": ["Scapular protraction", "Scapular upward rotation", "Holds scapula against chest wall"],
        "antagonists": ["Rhomboid major", "Rhomboid minor", "Trapezius (middle)"],
        "region": "Shoulder Girdle",
    },
    "trapezius": {
        "zh": "斜方肌",
        "origin": "Occipital bone (external protuberance); Nuchal ligament; Spinous processes C7-T12",
        "insertion": "Lateral third of clavicle; Acromion; Spine of scapula",
        "innervation": "Accessory nerve (CN XI); Cervical nerves C3-C4",
        "functions": ["Upper: Scapular elevation, Neck extension, Head rotation (contralateral); Middle: Scapular retraction; Lower: Scapular depression, Upward rotation"],
        "antagonists": ["Serratus anterior (retraction)", "Levator scapulae (antagonist for lower)"],
        "region": "Back / Shoulder Girdle",
    },
    "rhomboid major": {
        "zh": "大菱形肌",
        "origin": "Spinous processes T2-T5",
        "insertion": "Medial border of scapula (between spine and inferior angle)",
        "innervation": "Dorsal scapular nerve (C5)",
        "functions": ["Scapular retraction", "Scapular elevation", "Scapular downward rotation"],
        "antagonists": ["Serratus anterior", "Pectoralis minor"],
        "region": "Back",
    },
    "rhomboid minor": {
        "zh": "小菱形肌",
        "origin": "Ligamentum nuchae; Spinous processes C7-T1",
        "insertion": "Medial border of scapula at level of scapular spine",
        "innervation": "Dorsal scapular nerve (C5)",
        "functions": ["Scapular retraction", "Scapular elevation", "Scapular downward rotation"],
        "antagonists": ["Serratus anterior"],
        "region": "Back",
    },

    # ══════════════ 上臂 Upper Arm ══════════════
    "biceps brachii": {
        "zh": "肱二頭肌",
        "origin": "Short head: Coracoid process of scapula; Long head: Supraglenoid tubercle of scapula",
        "insertion": "Radial tuberosity; Bicipital aponeurosis (into antebrachial fascia)",
        "innervation": "Musculocutaneous nerve (C5-C7)",
        "functions": ["Elbow flexion", "Forearm supination", "Shoulder flexion (weak)", "Glenohumeral stabilization"],
        "antagonists": ["Triceps brachii"],
        "region": "Upper Arm",
    },
    "brachialis": {
        "zh": "肱肌",
        "origin": "Distal half of anterior surface of humerus",
        "insertion": "Coronoid process and tuberosity of ulna",
        "innervation": "Musculocutaneous nerve (C5-C6); Radial nerve (C7, partial)",
        "functions": ["Elbow flexion (primary)"],
        "antagonists": ["Triceps brachii"],
        "region": "Upper Arm",
    },
    "triceps brachii": {
        "zh": "肱三頭肌",
        "origin": "Long head: Infraglenoid tubercle of scapula; Lateral head: Posterior surface of humerus (proximal to radial groove); Medial head: Posterior surface of humerus (distal to radial groove)",
        "insertion": "Olecranon of ulna",
        "innervation": "Radial nerve (C6-C8)",
        "functions": ["Elbow extension", "Shoulder extension (long head)", "Shoulder adduction (long head)"],
        "antagonists": ["Biceps brachii", "Brachialis"],
        "region": "Upper Arm",
    },

    # ══════════════ 前臂 Forearm ══════════════
    "pronator teres": {
        "zh": "旋前圓肌",
        "origin": "Humeral head: Medial epicondyle (common flexor tendon); Ulnar head: Coronoid process of ulna",
        "insertion": "Lateral surface of radius (midshaft)",
        "innervation": "Median nerve (C6-C7)",
        "functions": ["Forearm pronation", "Elbow flexion (weak)"],
        "antagonists": ["Supinator", "Biceps brachii"],
        "region": "Forearm",
    },
    "pronator quadratus": {
        "zh": "旋前方肌",
        "origin": "Anterior surface of distal ulna (medial)",
        "insertion": "Anterior surface of distal radius (lateral)",
        "innervation": "Anterior interosseous nerve (C8-T1)",
        "functions": ["Forearm pronation"],
        "antagonists": ["Supinator", "Biceps brachii"],
        "region": "Forearm",
    },
    "supinator": {
        "zh": "旋後肌",
        "origin": "Lateral epicondyle of humerus; Radial collateral ligament; Annular ligament; Supinator crest of ulna",
        "insertion": "Anterior and lateral surfaces of proximal radius",
        "innervation": "Deep branch of radial nerve (C5-C6)",
        "functions": ["Forearm supination"],
        "antagonists": ["Pronator teres", "Pronator quadratus"],
        "region": "Forearm",
    },
    "brachioradialis": {
        "zh": "肱橈肌",
        "origin": "Lateral supracondylar ridge of humerus; Lateral intermuscular septum",
        "insertion": "Styloid process of radius",
        "innervation": "Radial nerve (C5-C6)",
        "functions": ["Elbow flexion (especially from midprone position)", "Forearm semi-pronation/supination"],
        "antagonists": ["Triceps brachii"],
        "region": "Forearm",
    },
    "flexor carpi radialis": {
        "zh": "橈側屈腕肌",
        "origin": "Medial epicondyle of humerus (common flexor tendon)",
        "insertion": "Bases of metacarpal bones 2-3",
        "innervation": "Median nerve (C6-C7)",
        "functions": ["Wrist flexion", "Wrist radial deviation", "Elbow flexion (weak)"],
        "antagonists": ["Extensor carpi radialis longus", "Extensor carpi radialis brevis"],
        "region": "Forearm",
    },
    "flexor carpi ulnaris": {
        "zh": "尺側屈腕肌",
        "origin": "Humeral head: Medial epicondyle; Ulnar head: Olecranon and posterior ulna",
        "insertion": "Pisiform; Hook of hamate; Base of metacarpal 5",
        "innervation": "Ulnar nerve (C7-T1)",
        "functions": ["Wrist flexion", "Wrist ulnar deviation"],
        "antagonists": ["Extensor carpi ulnaris"],
        "region": "Forearm",
    },
    "palmaris longus": {
        "zh": "掌長肌",
        "origin": "Medial epicondyle of humerus (common flexor tendon)",
        "insertion": "Flexor retinaculum; Palmar aponeurosis",
        "innervation": "Median nerve (C7-C8)",
        "functions": ["Wrist flexion (weak)", "Tenses palmar aponeurosis"],
        "antagonists": ["Wrist extensors"],
        "region": "Forearm",
    },
    "extensor carpi radialis longus": {
        "zh": "橈側伸腕長肌",
        "origin": "Lateral supracondylar ridge of humerus",
        "insertion": "Base of metacarpal bone 2",
        "innervation": "Radial nerve (C6-C7)",
        "functions": ["Wrist extension", "Wrist radial deviation", "Elbow flexion (weak)"],
        "antagonists": ["Flexor carpi radialis", "Flexor carpi ulnaris"],
        "region": "Forearm",
    },
    "extensor carpi radialis brevis": {
        "zh": "橈側伸腕短肌",
        "origin": "Lateral epicondyle of humerus (common extensor tendon)",
        "insertion": "Base of metacarpal bone 3",
        "innervation": "Deep branch of radial nerve (C6-C7)",
        "functions": ["Wrist extension", "Wrist radial deviation"],
        "antagonists": ["Flexor carpi radialis", "Flexor carpi ulnaris"],
        "region": "Forearm",
    },
    "extensor carpi ulnaris": {
        "zh": "尺側伸腕肌",
        "origin": "Lateral epicondyle of humerus (common extensor tendon); Posterior border of ulna",
        "insertion": "Base of metacarpal bone 5",
        "innervation": "Deep branch of radial nerve (C7-C8)",
        "functions": ["Wrist extension", "Wrist ulnar deviation"],
        "antagonists": ["Flexor carpi ulnaris"],
        "region": "Forearm",
    },
    "flexor digitorum superficialis": {
        "zh": "指淺屈肌",
        "origin": "Humeroulnar head: Medial epicondyle, Coronoid process; Radial head: Oblique line of radius",
        "insertion": "Sides of middle phalanges of digits 2-5",
        "innervation": "Median nerve (C7-T1)",
        "functions": ["Finger flexion (PIP joints 2-5)", "Wrist flexion"],
        "antagonists": ["Extensor digitorum"],
        "region": "Forearm",
    },
    "flexor digitorum profundus": {
        "zh": "指深屈肌",
        "origin": "Anteromedial surface of ulna; Interosseous membrane",
        "insertion": "Bases of distal phalanges of digits 2-5",
        "innervation": "Radial half (digits 2-3): Median nerve via anterior interosseous branch (C8-T1); Ulnar half (digits 4-5): Ulnar nerve (C8-T1)",
        "functions": ["Finger flexion (DIP joints 2-5)", "Wrist flexion"],
        "antagonists": ["Extensor digitorum"],
        "region": "Forearm",
    },
    "extensor digitorum": {
        "zh": "伸指肌",
        "origin": "Lateral epicondyle of humerus (common extensor tendon)",
        "insertion": "Extensor expansion of digits 2-5",
        "innervation": "Deep branch of radial nerve (C7-C8)",
        "functions": ["Finger extension (MCP, PIP, DIP joints 2-5)", "Wrist extension"],
        "antagonists": ["Flexor digitorum superficialis", "Flexor digitorum profundus"],
        "region": "Forearm",
    },

    # ══════════════ 腹部 Abdominal ══════════════
    "rectus abdominis": {
        "zh": "腹直肌",
        "origin": "Pubic crest; Pubic symphysis",
        "insertion": "Costal cartilages of ribs 5-7; Xiphoid process",
        "innervation": "Thoracoabdominal nerves (T7-T12)",
        "functions": ["Trunk flexion", "Pelvic posterior tilt", "Increases intra-abdominal pressure"],
        "antagonists": ["Erector spinae", "Multifidus"],
        "region": "Abdominal",
    },
    "external oblique": {
        "zh": "腹外斜肌",
        "origin": "External surfaces of lower 8 ribs (ribs 5-12)",
        "insertion": "Iliac crest (anterior half); Linea alba; Inguinal ligament",
        "innervation": "Thoracoabdominal nerves T8-T12; Iliohypogastric nerve (L1)",
        "functions": ["Trunk flexion (bilateral)", "Trunk rotation (contralateral)", "Trunk lateral flexion (ipsilateral)", "Compresses abdomen"],
        "antagonists": ["Erector spinae"],
        "region": "Abdominal",
    },
    "internal oblique": {
        "zh": "腹內斜肌",
        "origin": "Thoracolumbar fascia; Iliac crest; Lateral inguinal ligament",
        "insertion": "Costal cartilages of ribs 9-12; Linea alba",
        "innervation": "Thoracoabdominal nerves T10-T12; Iliohypogastric and ilioinguinal nerves (L1)",
        "functions": ["Trunk flexion (bilateral)", "Trunk rotation (ipsilateral)", "Trunk lateral flexion (ipsilateral)", "Compresses abdomen"],
        "antagonists": ["Erector spinae"],
        "region": "Abdominal",
    },
    "transversus abdominis": {
        "zh": "腹橫肌",
        "origin": "Lower 6 ribs (costal cartilages 7-12); Thoracolumbar fascia; Anterior 3/4 of iliac crest; Lateral 1/3 of inguinal ligament",
        "insertion": "Linea alba; Pubic crest",
        "innervation": "Thoracoabdominal nerves T7-T12; Iliohypogastric and ilioinguinal nerves (L1)",
        "functions": ["Abdominal compression", "Increases intra-abdominal pressure", "Core/trunk stabilization (key stabilizer)"],
        "antagonists": [],
        "region": "Abdominal",
    },

    # ══════════════ 背部 Back ══════════════
    "erector spinae": {
        "zh": "豎脊肌（髂肋肌＋最長肌＋棘肌）",
        "origin": "Common origin: Sacrum, Iliac crest, Lumbar spinous processes; Individual origins vary by component",
        "insertion": "Ribs; Transverse processes; Spinous processes; Occipital bone",
        "innervation": "Dorsal rami of corresponding spinal nerves",
        "functions": ["Trunk extension (bilateral)", "Trunk lateral flexion (ipsilateral)", "Head extension (cervical fibers)"],
        "antagonists": ["Rectus abdominis", "External oblique", "Internal oblique"],
        "region": "Back",
    },
    "multifidus": {
        "zh": "多裂肌",
        "origin": "Sacrum; Iliac crest; Transverse processes L1-L5; Articular processes C4-C7",
        "insertion": "Spinous processes 2-4 levels above origin",
        "innervation": "Dorsal rami of corresponding spinal nerves",
        "functions": ["Spinal extension", "Spinal rotation (contralateral)", "Segmental spinal stabilization (primary stabilizer)"],
        "antagonists": ["Rectus abdominis", "Obliques"],
        "region": "Back",
    },
    "quadratus lumborum": {
        "zh": "腰方肌",
        "origin": "Posterior iliac crest; Iliolumbar ligament",
        "insertion": "12th rib; Transverse processes L1-L4",
        "innervation": "Ventral rami T12, L1-L4",
        "functions": ["Trunk lateral flexion (ipsilateral)", "Hip elevation", "Fixes 12th rib during inspiration"],
        "antagonists": ["Contralateral quadratus lumborum", "Obliques"],
        "region": "Back",
    },

    # ══════════════ 頸部 Neck ══════════════
    "sternocleidomastoid": {
        "zh": "胸鎖乳突肌（SCM）",
        "origin": "Sternal head: Manubrium of sternum; Clavicular head: Medial third of clavicle",
        "insertion": "Mastoid process of temporal bone; Superior nuchal line",
        "innervation": "Accessory nerve (CN XI); Cervical plexus C2-C3",
        "functions": ["Bilateral: Neck flexion, Head protraction; Unilateral: Neck lateral flexion (ipsilateral), Head rotation (contralateral)"],
        "antagonists": ["Splenius capitis", "Trapezius (upper)"],
        "region": "Neck",
    },
    "levator scapulae": {
        "zh": "提肩胛肌",
        "origin": "Transverse processes of C1-C4",
        "insertion": "Medial border of scapula from superior angle to root of spine of scapula",
        "innervation": "Anterior rami C3-C4 and dorsal scapular nerve (C5)",
        "functions": ["Scapular elevation", "Scapular downward rotation", "Glenoid fossa inferior rotation", "Neck lateral flexion (ipsilateral)"],
        "antagonists": ["Trapezius (lower fibers)", "Serratus anterior (lower)"],
        "region": "Neck / Shoulder",
    },
    "splenius capitis": {
        "zh": "頭夾肌",
        "origin": "Nuchal ligament; Spinous processes C7-T3",
        "insertion": "Mastoid process; Lateral superior nuchal line",
        "innervation": "Lateral branches of dorsal rami C3-C5",
        "functions": ["Bilateral: Head/neck extension; Unilateral: Head rotation (ipsilateral), Lateral flexion (ipsilateral)"],
        "antagonists": ["Sternocleidomastoid", "Longus colli"],
        "region": "Neck",
    },
    "scalenes": {
        "zh": "斜角肌群（前/中/後）",
        "origin": "Anterior: Anterior tubercles of transverse processes C3-C6; Middle: Posterior tubercles C2-C7; Posterior: Posterior tubercles C4-C6",
        "insertion": "Anterior: Scalene tubercle of 1st rib; Middle: Upper surface of 1st rib; Posterior: Outer surface of 2nd rib",
        "innervation": "Anterior: Anterior rami C5-C8; Middle: Anterior rami C3-C7; Posterior: Anterior rami C5-C8",
        "functions": ["Bilateral: Neck flexion, Rib elevation (inspiration); Unilateral: Lateral flexion (ipsilateral), Rotation (contralateral)"],
        "antagonists": ["Splenius capitis", "Sternocleidomastoid (rotation)"],
        "region": "Neck",
    },
}

# ─────────────────────────────────────────
# 動作查詢對照表
# ─────────────────────────────────────────
MOVEMENTS = {
    # ── 髖關節 Hip ──
    "hip flexion": {
        "zh": "髖屈曲",
        "joint": "Hip Joint",
        "agonists":    ["iliopsoas", "rectus femoris"],
        "synergists":  ["sartorius", "pectineus", "tensor fasciae latae", "adductor longus", "adductor brevis", "gracilis"],
        "antagonists": ["gluteus maximus", "semimembranosus", "semitendinosus", "biceps femoris"],
    },
    "hip extension": {
        "zh": "髖伸展",
        "joint": "Hip Joint",
        "agonists":    ["gluteus maximus", "semimembranosus", "semitendinosus", "biceps femoris"],
        "synergists":  ["adductor magnus (ischiocondylar part)", "gluteus medius (posterior fibers)"],
        "antagonists": ["iliopsoas", "rectus femoris", "tensor fasciae latae", "sartorius"],
    },
    "hip abduction": {
        "zh": "髖外展",
        "joint": "Hip Joint",
        "agonists":    ["gluteus medius", "gluteus minimus"],
        "synergists":  ["tensor fasciae latae", "sartorius", "piriformis"],
        "antagonists": ["adductor longus", "adductor brevis", "adductor magnus", "gracilis", "pectineus"],
    },
    "hip adduction": {
        "zh": "髖內收",
        "joint": "Hip Joint",
        "agonists":    ["adductor longus", "adductor brevis", "adductor magnus"],
        "synergists":  ["gracilis", "pectineus", "obturator externus"],
        "antagonists": ["gluteus medius", "gluteus minimus", "tensor fasciae latae"],
    },
    "hip internal rotation": {
        "zh": "髖內轉",
        "joint": "Hip Joint",
        "agonists":    ["gluteus medius (anterior fibers)", "gluteus minimus", "tensor fasciae latae"],
        "synergists":  ["semimembranosus", "semitendinosus", "pectineus"],
        "antagonists": ["piriformis", "obturator internus", "obturator externus", "superior gemellus", "inferior gemellus", "quadratus femoris", "gluteus maximus"],
    },
    "hip external rotation": {
        "zh": "髖外轉",
        "joint": "Hip Joint",
        "agonists":    ["piriformis", "obturator internus", "obturator externus", "superior gemellus", "inferior gemellus", "quadratus femoris"],
        "synergists":  ["gluteus maximus", "sartorius", "biceps femoris (long head)"],
        "antagonists": ["gluteus medius (anterior)", "gluteus minimus", "tensor fasciae latae"],
    },
    # ── 膝關節 Knee ──
    "knee flexion": {
        "zh": "膝屈曲",
        "joint": "Knee Joint",
        "agonists":    ["semimembranosus", "semitendinosus", "biceps femoris"],
        "synergists":  ["gastrocnemius", "gracilis", "sartorius", "popliteus", "plantaris"],
        "antagonists": ["rectus femoris", "vastus medialis", "vastus lateralis", "vastus intermedius"],
    },
    "knee extension": {
        "zh": "膝伸展",
        "joint": "Knee Joint",
        "agonists":    ["rectus femoris", "vastus medialis", "vastus lateralis", "vastus intermedius"],
        "synergists":  ["tensor fasciae latae (via IT band)"],
        "antagonists": ["semimembranosus", "semitendinosus", "biceps femoris", "gastrocnemius", "gracilis"],
    },
    "knee internal rotation": {
        "zh": "膝內轉",
        "joint": "Knee Joint",
        "agonists":    ["semimembranosus", "semitendinosus", "gracilis"],
        "synergists":  ["sartorius", "popliteus"],
        "antagonists": ["biceps femoris"],
    },
    "knee external rotation": {
        "zh": "膝外轉",
        "joint": "Knee Joint",
        "agonists":    ["biceps femoris"],
        "synergists":  ["tensor fasciae latae"],
        "antagonists": ["semimembranosus", "semitendinosus", "gracilis", "sartorius"],
    },
    # ── 踝關節 Ankle ──
    "ankle dorsiflexion": {
        "zh": "踝背屈",
        "joint": "Talocrural Joint",
        "agonists":    ["tibialis anterior"],
        "synergists":  ["extensor digitorum longus", "extensor hallucis longus", "fibularis tertius"],
        "antagonists": ["gastrocnemius", "soleus", "plantaris", "tibialis posterior", "flexor digitorum longus", "flexor hallucis longus"],
    },
    "ankle plantarflexion": {
        "zh": "踝蹠屈",
        "joint": "Talocrural Joint",
        "agonists":    ["gastrocnemius", "soleus"],
        "synergists":  ["plantaris", "tibialis posterior", "fibularis longus", "fibularis brevis", "flexor digitorum longus", "flexor hallucis longus"],
        "antagonists": ["tibialis anterior", "extensor digitorum longus", "extensor hallucis longus"],
    },
    "foot inversion": {
        "zh": "足內翻",
        "joint": "Subtalar Joint",
        "agonists":    ["tibialis posterior"],
        "synergists":  ["tibialis anterior", "flexor hallucis longus", "flexor digitorum longus"],
        "antagonists": ["fibularis longus", "fibularis brevis", "extensor digitorum longus"],
    },
    "foot eversion": {
        "zh": "足外翻",
        "joint": "Subtalar Joint",
        "agonists":    ["fibularis longus", "fibularis brevis"],
        "synergists":  ["extensor digitorum longus", "fibularis tertius"],
        "antagonists": ["tibialis posterior", "tibialis anterior", "flexor hallucis longus"],
    },
    # ── 肩關節 Shoulder ──
    "shoulder flexion": {
        "zh": "肩屈曲",
        "joint": "Glenohumeral Joint",
        "agonists":    ["deltoid (anterior)", "pectoralis major (clavicular head)"],
        "synergists":  ["coracobrachialis", "biceps brachii (long head)", "supraspinatus"],
        "antagonists": ["deltoid (posterior)", "latissimus dorsi", "teres major", "pectoralis major (sternocostal)"],
    },
    "shoulder extension": {
        "zh": "肩伸展",
        "joint": "Glenohumeral Joint",
        "agonists":    ["deltoid (posterior)", "latissimus dorsi", "teres major"],
        "synergists":  ["pectoralis major (sternocostal head)", "triceps brachii (long head)"],
        "antagonists": ["deltoid (anterior)", "pectoralis major (clavicular head)", "coracobrachialis"],
    },
    "shoulder abduction": {
        "zh": "肩外展",
        "joint": "Glenohumeral Joint",
        "agonists":    ["deltoid (middle)", "supraspinatus"],
        "synergists":  ["serratus anterior", "trapezius (upward rotation)", "biceps brachii (long head)"],
        "antagonists": ["pectoralis major", "latissimus dorsi", "teres major"],
    },
    "shoulder adduction": {
        "zh": "肩內收",
        "joint": "Glenohumeral Joint",
        "agonists":    ["pectoralis major", "latissimus dorsi", "teres major"],
        "synergists":  ["coracobrachialis", "subscapularis", "teres minor", "triceps brachii (long head)"],
        "antagonists": ["deltoid (middle)", "supraspinatus"],
    },
    "shoulder internal rotation": {
        "zh": "肩內轉",
        "joint": "Glenohumeral Joint",
        "agonists":    ["subscapularis"],
        "synergists":  ["pectoralis major", "latissimus dorsi", "teres major", "deltoid (anterior)"],
        "antagonists": ["infraspinatus", "teres minor", "deltoid (posterior)"],
    },
    "shoulder external rotation": {
        "zh": "肩外轉",
        "joint": "Glenohumeral Joint",
        "agonists":    ["infraspinatus", "teres minor"],
        "synergists":  ["deltoid (posterior)"],
        "antagonists": ["subscapularis", "pectoralis major", "latissimus dorsi", "teres major"],
    },
    "shoulder horizontal abduction": {
        "zh": "肩水平外展",
        "joint": "Glenohumeral Joint",
        "agonists":    ["deltoid (posterior)"],
        "synergists":  ["infraspinatus", "teres minor", "rhomboids"],
        "antagonists": ["pectoralis major", "coracobrachialis", "deltoid (anterior)"],
    },
    "shoulder horizontal adduction": {
        "zh": "肩水平內收",
        "joint": "Glenohumeral Joint",
        "agonists":    ["pectoralis major", "deltoid (anterior)"],
        "synergists":  ["coracobrachialis", "subscapularis"],
        "antagonists": ["deltoid (posterior)", "infraspinatus", "teres minor"],
    },
    # ── 肩胛骨 Scapular ──
    "scapular elevation": {
        "zh": "肩胛骨上提",
        "joint": "Scapulothoracic Joint",
        "agonists":    ["trapezius (upper fibers)", "levator scapulae"],
        "synergists":  ["rhomboid major", "rhomboid minor"],
        "antagonists": ["trapezius (lower fibers)", "serratus anterior (lower)"],
    },
    "scapular depression": {
        "zh": "肩胛骨下壓",
        "joint": "Scapulothoracic Joint",
        "agonists":    ["trapezius (lower fibers)", "serratus anterior (lower fibers)"],
        "synergists":  ["pectoralis minor", "latissimus dorsi"],
        "antagonists": ["trapezius (upper)", "levator scapulae"],
    },
    "scapular retraction": {
        "zh": "肩胛骨後縮",
        "joint": "Scapulothoracic Joint",
        "agonists":    ["rhomboid major", "rhomboid minor"],
        "synergists":  ["trapezius (middle fibers)"],
        "antagonists": ["serratus anterior", "pectoralis minor"],
    },
    "scapular protraction": {
        "zh": "肩胛骨前突",
        "joint": "Scapulothoracic Joint",
        "agonists":    ["serratus anterior"],
        "synergists":  ["pectoralis minor"],
        "antagonists": ["rhomboid major", "rhomboid minor", "trapezius (middle)"],
    },
    "scapular upward rotation": {
        "zh": "肩胛骨向上旋轉",
        "joint": "Scapulothoracic Joint",
        "agonists":    ["trapezius (upper and lower)", "serratus anterior"],
        "synergists":  [],
        "antagonists": ["rhomboids", "levator scapulae", "pectoralis minor"],
    },
    # ── 肘關節 Elbow ──
    "elbow flexion": {
        "zh": "肘屈曲",
        "joint": "Elbow Joint",
        "agonists":    ["biceps brachii", "brachialis"],
        "synergists":  ["brachioradialis", "pronator teres"],
        "antagonists": ["triceps brachii", "anconeus"],
    },
    "elbow extension": {
        "zh": "肘伸展",
        "joint": "Elbow Joint",
        "agonists":    ["triceps brachii"],
        "synergists":  ["anconeus"],
        "antagonists": ["biceps brachii", "brachialis", "brachioradialis"],
    },
    "forearm supination": {
        "zh": "前臂旋後",
        "joint": "Radioulnar Joint",
        "agonists":    ["supinator", "biceps brachii"],
        "synergists":  [],
        "antagonists": ["pronator teres", "pronator quadratus"],
    },
    "forearm pronation": {
        "zh": "前臂旋前",
        "joint": "Radioulnar Joint",
        "agonists":    ["pronator teres", "pronator quadratus"],
        "synergists":  ["flexor carpi radialis"],
        "antagonists": ["supinator", "biceps brachii"],
    },
    # ── 腕關節 Wrist ──
    "wrist flexion": {
        "zh": "腕屈曲",
        "joint": "Wrist Joint",
        "agonists":    ["flexor carpi radialis", "flexor carpi ulnaris"],
        "synergists":  ["palmaris longus", "flexor digitorum superficialis", "flexor digitorum profundus"],
        "antagonists": ["extensor carpi radialis longus", "extensor carpi radialis brevis", "extensor carpi ulnaris"],
    },
    "wrist extension": {
        "zh": "腕伸展",
        "joint": "Wrist Joint",
        "agonists":    ["extensor carpi radialis longus", "extensor carpi radialis brevis", "extensor carpi ulnaris"],
        "synergists":  ["extensor digitorum", "extensor indicis"],
        "antagonists": ["flexor carpi radialis", "flexor carpi ulnaris"],
    },
    "wrist radial deviation": {
        "zh": "腕橈偏",
        "joint": "Wrist Joint",
        "agonists":    ["flexor carpi radialis", "extensor carpi radialis longus"],
        "synergists":  ["extensor carpi radialis brevis"],
        "antagonists": ["flexor carpi ulnaris", "extensor carpi ulnaris"],
    },
    "wrist ulnar deviation": {
        "zh": "腕尺偏",
        "joint": "Wrist Joint",
        "agonists":    ["flexor carpi ulnaris", "extensor carpi ulnaris"],
        "synergists":  [],
        "antagonists": ["flexor carpi radialis", "extensor carpi radialis longus"],
    },
    # ── 脊椎 Spine ──
    "trunk flexion": {
        "zh": "軀幹屈曲",
        "joint": "Spine",
        "agonists":    ["rectus abdominis"],
        "synergists":  ["external oblique", "internal oblique"],
        "antagonists": ["erector spinae", "multifidus"],
    },
    "trunk extension": {
        "zh": "軀幹伸展",
        "joint": "Spine",
        "agonists":    ["erector spinae"],
        "synergists":  ["multifidus", "quadratus lumborum", "gluteus maximus"],
        "antagonists": ["rectus abdominis", "external oblique", "internal oblique"],
    },
    "trunk rotation": {
        "zh": "軀幹旋轉",
        "joint": "Spine",
        "agonists":    ["external oblique (contralateral)", "internal oblique (ipsilateral)"],
        "synergists":  ["multifidus", "erector spinae (ipsilateral)"],
        "antagonists": ["Contralateral obliques"],
    },
    "trunk lateral flexion": {
        "zh": "軀幹側屈",
        "joint": "Spine",
        "agonists":    ["quadratus lumborum", "erector spinae (ipsilateral)"],
        "synergists":  ["external oblique (ipsilateral)", "internal oblique (ipsilateral)", "psoas major"],
        "antagonists": ["Contralateral quadratus lumborum and erector spinae"],
    },
    # ── 頸椎 Cervical ──
    "neck flexion": {
        "zh": "頸屈曲",
        "joint": "Cervical Spine",
        "agonists":    ["sternocleidomastoid (bilateral)"],
        "synergists":  ["scalenes", "longus colli (deep cervical flexors)"],
        "antagonists": ["splenius capitis", "erector spinae (cervical)", "trapezius (upper)"],
    },
    "neck extension": {
        "zh": "頸伸展",
        "joint": "Cervical Spine",
        "agonists":    ["splenius capitis", "erector spinae (cervical)"],
        "synergists":  ["trapezius (upper fibers)", "semispinalis capitis"],
        "antagonists": ["sternocleidomastoid", "scalenes"],
    },
    "neck rotation": {
        "zh": "頸旋轉",
        "joint": "Cervical Spine",
        "agonists":    ["sternocleidomastoid (contralateral)", "splenius capitis (ipsilateral)"],
        "synergists":  ["scalenes (contralateral)", "semispinalis cervicis"],
        "antagonists": ["Contralateral rotators"],
    },
    "neck lateral flexion": {
        "zh": "頸側屈",
        "joint": "Cervical Spine",
        "agonists":    ["sternocleidomastoid (ipsilateral)", "scalenes (ipsilateral)"],
        "synergists":  ["levator scapulae", "splenius capitis (ipsilateral)"],
        "antagonists": ["Contralateral neck muscles"],
    },
}

# 別名對應（中文 / 縮寫 / 常用名）
ALIASES = {
    "hamstrings": ["semimembranosus", "semitendinosus", "biceps femoris"],
    "quadriceps": ["rectus femoris", "vastus medialis", "vastus lateralis", "vastus intermedius"],
    "rotator cuff": ["supraspinatus", "infraspinatus", "teres minor", "subscapularis"],
    "iliopsoas": ["iliopsoas"],
    "triceps surae": ["gastrocnemius", "soleus"],
    "hip flexors": ["iliopsoas", "rectus femoris", "sartorius", "tensor fasciae latae"],
    "hip abductors": ["gluteus medius", "gluteus minimus", "tensor fasciae latae"],
    "hip external rotators": ["piriformis", "obturator internus", "obturator externus", "superior gemellus", "inferior gemellus", "quadratus femoris"],
    # Chinese aliases
    "腿後腱肌": ["semimembranosus", "semitendinosus", "biceps femoris"],
    "股四頭肌": ["rectus femoris", "vastus medialis", "vastus lateralis", "vastus intermedius"],
    "旋轉肌袖": ["supraspinatus", "infraspinatus", "teres minor", "subscapularis"],
    "小腿三頭肌": ["gastrocnemius", "soleus"],
}


# ─────────────────────────────────────────
# 資料來源
# ─────────────────────────────────────────
SOURCES = [
    {
        "name": "UAMS – Muscle Tables (Primary Source)",
        "url": "https://medicine.uams.edu/neuroscience/education/medical-school-courses/human-structure-module/anatomy-tables/muscle-tables/",
        "note": "University of Arkansas for Medical Sciences, Human Structure Module（主要來源，所有分區完整比對驗證）"
    },
    {
        "name": "Kenhub – Lower Limb Muscle Charts (Primary Source)",
        "url": "https://www.kenhub.com",
        "note": "下肢肌肉 Cheat Sheet (English Terminology)（主要來源）"
    },
    {
        "name": "Gray\'s Anatomy (40th Edition)",
        "url": "https://en.wikipedia.org/wiki/Gray%27s_Anatomy",
        "note": "Standard anatomical reference（補充參考）"
    },
    {
        "name": "Wikipedia – Individual Muscle Articles",
        "url": "https://en.wikipedia.org/wiki/Muscle",
        "note": "各條肌肉的 Wikipedia 頁面（補充參考）"
    },
    {
        "name": "Gray's Anatomy (Grays Anatomy for Students)",
        "url": "https://en.wikipedia.org/wiki/Gray%27s_Anatomy",
        "note": "第三來源，用於交叉驗證（Primary Source）"
    },
]
